server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=${JWT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.reset-password-url=${FRONTEND_RESET_PASSWORD_URL}

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.validation-timeout=5000

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.cookie.secure=${COOKIE_SECURE:true}
app.cookie.same-site=${COOKIE_SAME_SITE:None}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE:false}
spring.flyway.baseline-version=1

app.scheduler.overdue-loans-cron=${OVERDUE_LOANS_CRON:0 */10 * * * *}

stripe.success-url=${STRIPE_SUCCESS_URL}
stripe.cancel-url=${STRIPE_CANCEL_URL}

app.scheduler.auto-renew-cron=${AUTO_RENEW_CRON:0 */30 * * * *}
app.scheduler.reservation-expiration-cron=${RESERVATION_EXPIRATION_CRON:0 */10 * * * *}
app.scheduler.subscription-expiration-cron=${SUBSCRIPTION_EXPIRATION_CRON:0 */15 * * * *}


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

management.health.mail.enabled=false